FROM python:3.10-alpine

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app
ENV PYTHONPATH "${PYTHONPATH}:/app"

CMD ["python", "-u", "main.py", "--start"]