version: '3'
services:
  opensearch-node:
    image: opensearchproject/opensearch:2.8.0
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - app-network
    restart: always
    
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]'
    networks:
      - app-network

  fastapi-server:
    container_name: fastapi-server
    build: ./backend
    ports: 
      - 8080:80
    networks:
      - app-network
    env_file:
      - .env
    environment:
      ENV_OS_HOST: "opensearch-node"
    restart: always

volumes:
  opensearch-data:

networks:
  app-network: